In [79]:
import pandas as pd
import numpy as np

In [80]:
# file is in arff format
with open("ECG5000/ECG5000_TRAIN.arff", "r") as f:
    train = f.readlines()

with open("ECG5000/ECG5000_TEST.arff", "r") as f:
    test = f.readlines()

with open("ECG5000.csv", "w") as f:
    f.writelines(train[145:])
    f.writelines(test[145:])

In [81]:
data = pd.read_csv("ECG5000.csv", header=None)
data.describe()

,0,1,2,3,4,5,6,7,8,9,...,131,132,133,134,135,136,137,138,139,140
count,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,...,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000
mean,-0.262476,-1.649511,-2.492211,-3.119443,-3.167438,-2.866308,-2.273126,-1.798127,-1.410124,-0.936082,...,0.070973,-0.062914,-0.276206,-0.507667,-0.761043,-0.834741,-0.642263,-0.487242,-0.706008,1.527400
std,1.152369,1.445493,1.386409,1.302802,1.104382,0.906133,0.731627,0.623100,0.637149,0.657945,...,1.404842,1.646585,1.895134,2.059758,2.086218,2.056220,1.859296,1.830987,1.414465,0.760372
min,-6.729499,-7.090374,-5.132459,-5.363241,-5.375715,-5.330194,-4.782240,-4.311288,-4.071361,-4.142476,...,-4.167040,-4.557576,-4.530488,-4.563270,-5.150100,-4.880460,-5.496107,-5.880890,-6.092227,1.000000
25%,-1.004511,-2.701576,-3.668096,-4.227247,-4.007470,-3.480479,-2.779941,-2.165851,-1.774124,-1.362068,...,-1.089300,-1.588885,-2.147449,-2.731550,-3.030509,-2.868331,-2.153513,-1.657771,-1.596692,1.000000
50%,-0.297541,-1.661892,-2.585677,-3.387934,-3.468718,-2.947061,-2.285578,-1.750157,-1.422570,-0.910487,...,0.658318,0.717808,0.604747,0.334857,-0.030767,-0.195151,-0.194423,-0.160262,-0.565588,1.000000
75%,0.500061,-0.677290,-1.513964,-2.235369,-2.530967,-2.398813,-1.823494,-1.484923,-1.063708,-0.476660,...,1.169420,1.238687,1.264471,1.234433,1.034584,0.945237,0.951681,1.002692,0.272012,2.000000
max,4.966414,3.479689,2.660597,1.899798,2.147015,1.614375,1.868728,1.804251,1.683730,1.898627,...,3.007606,2.854680,2.912394,2.937685,3.351437,3.432519,3.579448,4.425976,7.402103,5.000000

In [82]:
data.head()

,0,1,2,3,4,5,6,7,8,9,...,131,132,133,134,135,136,137,138,139,140
0,-0.112522,-2.827204,-3.773897,-4.349751,-4.376041,-3.474986,-2.181408,-1.818286,-1.250522,-0.477492,...,0.792168,0.933541,0.796958,0.578621,0.257740,0.228077,0.123431,0.925286,0.193137,1
1,-1.100878,-3.996840,-4.285843,-4.506579,-4.022377,-3.234368,-1.566126,-0.992258,-0.754680,0.042321,...,0.538356,0.656881,0.787490,0.724046,0.555784,0.476333,0.773820,1.119621,-1.436250,1
2,-0.567088,-2.593450,-3.874230,-4.584095,-4.187449,-3.151462,-1.742940,-1.490659,-1.183580,-0.394229,...,0.886073,0.531452,0.311377,-0.021919,-0.713683,-0.532197,0.321097,0.904227,-0.421797,1
3,0.490473,-1.914407,-3.616364,-4.318823,-4.268016,-3.881110,-2.993280,-1.671131,-1.333884,-0.965629,...,0.350816,0.499111,0.600345,0.842069,0.952074,0.990133,1.086798,1.403011,-0.383564,1
4,0.800232,-0.874252,-2.384761,-3.973292,-4.338224,-3.802422,-2.534510,-1.783423,-1.594450,-0.753199,...,1.148884,0.958434,1.059025,1.371682,1.277392,0.960304,0.971020,1.614392,1.421456,1

In [83]:
data_normal = data[data[140] == 1]
data_normal[140].value_counts()

1    2919
Name: 140, dtype: int64

In [84]:
train_val_test_split = np.arange(data_normal.shape[0])
np.random.seed(0)
np.random.shuffle(train_val_test_split)
train_val_test_split

array([1815, 2871, 1232, ..., 1653, 2607, 2732])

In [85]:
train_size = int(len(train_val_test_split) * 0.8)
val_size = int(len(train_val_test_split) * 0.1)

In [86]:
data_train = data_normal.iloc[train_val_test_split[:train_size]]
data_val = data_normal.iloc[train_val_test_split[train_size:train_size+val_size]]
data_test = data_normal.iloc[train_val_test_split[train_size+val_size:]]

In [87]:
data_train.drop(140, axis=1).to_csv("train.csv", index=None)
data_train[140].to_csv("train_labels.csv", index=None)
data_val.drop(140, axis=1).to_csv("val.csv", index=None)
data_val[140].to_csv("val_labels.csv", index=None)
data_test.drop(140, axis=1).to_csv("test.csv", index=None)
data_test[140].to_csv("test_labels.csv", index=None)